name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  find-servers:
    name: Find Servers
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out servers repository (to discover subfolders)
        uses: actions/checkout@v3
        with:
          repository: modelcontextprotocol/servers
          ref: main
          path: servers

      - name: Discover server directories
        id: set-matrix
        run: |
          # Find all directories directly under "servers/src"
          servers=$(find servers/src -mindepth 1 -maxdepth 1 -type d)
          echo "Found servers in servers/src:"
          echo "$servers"

          # Build matrix JSON for each valid directory that has a Dockerfile
          matrix="{\"include\":["
          first=true
          for server in $servers; do
            dir_name=$(basename "$server")
            if [ ! -f "$server/Dockerfile" ]; then
              echo "No Dockerfile in $server; skipping."
              continue
            fi

            if [ "$first" = true ]; then
              first=false
            else
              matrix="$matrix,"
            fi
            matrix="$matrix{\"server\":\"$dir_name\"}"
          done
          matrix="$matrix]}"

          echo "Matrix: $matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-and-deploy:
    name: Build and Deploy
    needs: [find-servers]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find-servers.outputs.matrix) }}

    steps:
      # 1) Check out the current repo that contains uv.lock / pyproject.toml
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          path: this-repo  # now we can access "this-repo/uv.lock"

      # 2) Check out the servers repository again so we can build from it
      - name: Check out servers repository
        uses: actions/checkout@v3
        with:
          repository: modelcontextprotocol/servers
          ref: main
          path: servers  # this will be our build context

      # 3) Copy uv.lock and (optionally) pyproject.toml into servers/
      - name: Copy build files into Docker context
        run: |
          # Copy uv.lock if present
          if [ -f this-repo/uv.lock ]; then
            cp this-repo/uv.lock servers/uv.lock
            echo "Copied uv.lock -> servers/uv.lock"
          else
            echo "No uv.lock found in this-repo"
          fi

          # Copy pyproject.toml if present
          if [ -f this-repo/pyproject.toml ]; then
            cp this-repo/pyproject.toml servers/pyproject.toml
            echo "Copied pyproject.toml -> servers/pyproject.toml"
          else
            echo "No pyproject.toml found in this-repo"
          fi

      # 4) Debug step: Show the contents of servers/
      - name: List files in build context
        run: |
          echo "Listing servers/ directory:"
          ls -al servers/
          echo ""
          echo "Check if .dockerignore in servers/ is excluding uv.lock or pyproject.toml."

      # 5) Build Docker image from the subfolder's Dockerfile
      - name: Build Docker image
        run: |
          docker build \
            --file "servers/src/${{ matrix.server }}/Dockerfile" \
            --tag "yourorg/${{ matrix.server }}:latest" \
            servers
