name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  find-servers:
    name: Find Servers
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out servers repository (to discover subfolders)
        uses: actions/checkout@v3
        with:
          repository: modelcontextprotocol/servers
          ref: main
          path: servers

      - name: Discover server directories
        id: set-matrix
        run: |
          # Find all directories directly under "servers/src"
          servers=$(find servers/src -mindepth 1 -maxdepth 1 -type d)
          echo "Found servers in servers/src:"
          echo "$servers"

          # Build matrix JSON for each valid directory that has a Dockerfile
          matrix="{\"include\":["
          first=true
          for server in $servers; do
            dir_name=$(basename "$server")
            if [ ! -f "$server/Dockerfile" ]; then
              echo "No Dockerfile in $server; skipping."
              continue
            fi

            if [ "$first" = true ]; then
              first=false
            else
              matrix="$matrix,"
            fi
            matrix="$matrix{\"server\":\"$dir_name\"}"
          done
          matrix="$matrix]}"

          echo "Matrix: $matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-and-deploy:
    name: Build and Deploy
    needs: [find-servers]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find-servers.outputs.matrix) }}

    steps:
      # 1) Check out this repo
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          path: this-repo

      # 2) Check out the servers repo
      - name: Check out servers repository
        uses: actions/checkout@v3
        with:
          repository: modelcontextprotocol/servers
          ref: main
          path: servers

      # 3) Optionally copy uv.lock and pyproject.toml
      - name: Copy local uv.lock and pyproject.toml
        run: |
          if [ -f "servers/src/${{ matrix.server }}/uv.lock" ]; then
            cp "servers/src/${{ matrix.server }}/uv.lock" servers/uv.lock
            echo "Copied uv.lock up to servers/uv.lock"
          fi
          if [ -f "servers/src/${{ matrix.server }}/pyproject.toml" ]; then
            cp "servers/src/${{ matrix.server }}/pyproject.toml" servers/pyproject.toml
            echo "Copied pyproject.toml up to servers/pyproject.toml"
          fi

      # 4) Debug listing
      - name: List files in build context
        run: |
          echo "Listing servers/ after copying any uv.lock or pyproject.toml:"
          ls -al servers

      # 5) Check for pyproject.toml and set a 'skip_build' output
      - name: Check for pyproject.toml
        id: check-uvlock
        run: |
          if [ -f "servers/src/${{ matrix.server }}/pyproject.toml" ]; then
            echo "pyproject.toml found for ${{ matrix.server }}; build will be skipped."
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "No pyproject.toml found for ${{ matrix.server }}."
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

      # 6) Create directory (named as the server) and put README.md in it
      - name: Create directory and copy README.md
        if: steps.check-uvlock.outputs.skip_build == 'false'
        run: |
          mkdir -p "this-repo/${{ matrix.server }}"
          if [ -f "servers/src/${{ matrix.server }}/README.md" ]; then
            cp "servers/src/${{ matrix.server }}/README.md" "this-repo/${{ matrix.server }}/README.md"
            echo "README.md copied to this-repo/${{ matrix.server }}/"
          else
            echo "No README.md found for ${{ matrix.server }}; skipping copy."
          fi

      # 7) Build the Docker image, only if skip_build == 'false'
      - name: Build Docker image
        if: steps.check-uvlock.outputs.skip_build == 'false'
        run: |
          docker build \
            --file "servers/src/${{ matrix.server }}/Dockerfile" \
            --tag "yourorg/${{ matrix.server }}:latest" \
            servers
